on:
  push:
    branches:
      - main
    paths: ['backend/**', '.github/workflows/prod-backend.yml']

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy-backend-prod:
    runs-on: ubuntu-latest
    name: Deploy to prod
    if: github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
      - name: pnpm install
        run: pnpm install
      - name: Deploy migrations
        run: pnpm db:deploy-migrations
      - name: Deploy to prod
        run: |
          ~/.fly/bin/fly deploy \
            --config fly.backend.toml \
            --dockerfile ./backend/Dockerfile \
            --app culero-stage-api \
            --access-token ${{ secrets.FLY_ACCESS_TOKEN }}
